#spring.application.name=backend
spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/muhe?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 514179
    driver-class-name:  com.mysql.cj.jdbc.Driver

